# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COVER', 'COVER'), ('INTRO', 'INTRO'), ('DESCRIPTION', 'DESCRIPTION'), ('IMAGE', 'IMAGE'), ('IMAGE-IMAGE', 'IMAGE-IMAGE')], default='COVER', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('DISABLED', 'DISABLED')], default='CREATED', max_length=20)),
                ('categories', models.ManyToManyField(to='portfolio.Category')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='images',
            field=models.ManyToManyField(to='portfolio.Image'),
        ),
        migrations.AddField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
