# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='element',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.Element'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(default='https://placehold.it/350x150', max_length=500),
        ),
    ]
