# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
