# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160324_0127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='Block',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='element',
            new_name='block',
        ),
    ]
