# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160324_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('INTRO', 'INTRO'), ('DESCRIPTION', 'DESCRIPTION')], default='IMAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
