# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='content',
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE')], default='IMAGE', max_length=20),
        ),
    ]
